[workspace]
members = [
    # Packages
    "packages/sycamore",
    "packages/sycamore-macro",
    "packages/sycamore-reactive",

    # Examples
    "examples/context",
    "examples/counter",
    "examples/hello-world",
]
