[package]
name = "sycamore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore-reactive = { path = "../sycamore-reactive" }
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = { version = "0.4.28", optional = true }

[dependencies.lexical]
version = "6.0.1"
default-features = false
features = ["write-integers", "write-floats", "compact"]

[dependencies.web-sys]
features = [
    "console",
    "Comment",
    "Document",
    "DocumentFragment",
    "DomTokenList",
    "Element",
    "Event",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlCollection",
    "Node",
    "NodeList",
    "Text",
    "Window",
]
version = "0.3.55"

[dev-dependencies]
criterion = "0.3.5"

[features]
# default = ["dom", "wasm-bindgen-interning"]
default = ["dom"]
dom = []
experimental-builder-agnostic = []
experimental-builder-html = ["experimental-builder-agnostic"]
# experimental-hydrate = ["sycamore-macro/experimental-hydrate"]
futures = ["wasm-bindgen-futures"]
# ssr = ["html-escape", "once_cell", "experimental-hydrate", "sycamore-macro/ssr"]
# serde = ["sycamore-reactive/serde"]
wasm-bindgen-interning = ["wasm-bindgen/enable-interning"]

[[bench]]
harness = false
name = "reactivity"
