[package]
name = "sycamore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore-reactive = { path = "../sycamore-reactive" }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
harness = false
name = "reactivity"
